### PR TITLE
Adding venv, formatter and vscode plug ins

### PR DESCRIPTION
**Pull request by hupratt**
Olá viva, 

Wouldn't it be better to isolate the environments so that you have reproducibility between your local set up and production? 

Cheers, 

Hugo

### CODE REVIEW

**Comment by JoaquimEsteves** [comment]
Viva Hugo,

First of all, thanks for contributing. I'll be combing through your commits and I'll pick and choose some of your additions.

A bit of history: This repo was supposed to be a quick and dirty "copy-paste" type of deal, I like it that way as some of your choices are controversial among the grander Python community.

For example virtual environments, I personally use venv like yourself, but it's not a [clear choice for lots of others](https://stackoverflow.com/a/41573588).  

Ideally, a team _would_ have a more complete setup, but I've gotten into too many internet fights over how good [this](https://github.com/psf/black) or [that](https://github.com/hhatto/autopep8) tool is better, and as such I'd like to keep things generic, and tailor the settings for each project.

Kind regards,
Joaquim Esteves

**Comment by JoaquimEsteves** [comment]
Merged into master (with tweaks).

Basically made the settings/extensions more generic, and padded the readme.

**Comment by hupratt** [comment]
Viva Joaquim,

Ah ok, quando vi o teu repo estava com medo que nunca tivesses usado venv. 
Mas o repo é para ti ou para os outros? Se for para ti faz sentido criar uma parametragem "opinionated" para não perder tempo. Os outros que se lixem 😄

Bem vindo ao Luxemburgo by the way

Cheers,

**Comment by JoaquimEsteves** [comment]
Oi,

Isto é generico com uma licensa GLP, ou seja é para quem quiser.

> Os outros que se lixem smile

😂

Obrigado pelas boas vindas : )

**Pull request merged**
